# Generated by Django 5.0.4 on 2025-05-04 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_management', '0004_product_img_url'),
        ('user_management', '0002_delete_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='wishlist',
            field=models.ManyToManyField(blank=True, related_name='wishlisted_by', to='product_management.product'),
        ),
    ]
