services:
  - type: web
    name: ecoreachdb-api
    env: python
    buildCommand: cd ecommerce && pip install -r requirements.txt
    startCommand: >
      cd ecommerce &&
      python manage.py migrate &&
      python manage.py loaddata products.json users.json &&
      gunicorn ecommerce_service.wsgi:application --bind 0.0.0.0:$PORT
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: ecoreachdb
          property: connectionString
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: DEBUG
        value: false
      - key: ALLOWED_HOSTS
        value: ".onrender.com"

  - type: web
    name: ecoreachdb-frontend
    env: node
    buildCommand: cd app_frontend && npm install && npm run build
    startCommand: cd app_frontend && npm start
    envVars:
      - key: NODE_VERSION
        value: 18.0.0

databases:
  - name: ecoreachdb
    databaseName: ecoreachdb
    user: postgres
    plan: free 