# Generated by Django 5.0.4 on 2025-05-13 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('product_id', models.CharField(blank=True, max_length=20, primary_key=True, serialize=False, unique=True)),
                ('product_name', models.CharField(blank=True, max_length=255, null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('stock', models.PositiveIntegerField(default=1)),
                ('category', models.CharField(blank=True, max_length=100, null=True)),
                ('is_new_release', models.BooleanField(default=False)),
                ('is_trending', models.BooleanField(default=False)),
                ('rating', models.CharField(choices=[('0', '0'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], default='0', max_length=1)),
                ('description', models.TextField(blank=True, max_length=300, null=True)),
                ('detail', models.TextField(blank=True, max_length=300, null=True)),
                ('eco_point', models.DecimalField(decimal_places=0, default=0, max_digits=3)),
                ('img_url', models.URLField(blank=True, max_length=500, null=True)),
            ],
        ),
    ]
