# Generated by Django 5.0.4 on 2025-05-04 20:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product_management', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='is_new_release',
        ),
    ]
