# Generated by Django 5.0.4 on 2025-05-04 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_management', '0002_remove_product_is_new_release'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_new_release',
            field=models.BooleanField(default=False),
        ),
    ]
