# Generated by Django 5.0.4 on 2025-05-04 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_management', '0003_product_is_new_release'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='img_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
