# Generated by Django 5.0.4 on 2025-05-04 20:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order_management', '0001_initial'),
    ]

    operations = [
    ]
